name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  cross_build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Create build directory
        run: mkdir build

      - name: Configure project
        run: cmake -S . -B build

      - name: Build project
        run: cmake --build build

      - name: Run tests
        run: ctest --test-dir build -C Debug --output-on-failure
